#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect above requirements
# (this script will be run on the server itself)

# Install nginx
sudo apt-get update
sudo apt-get -y install nginx

mkdir /etc/nginx/html
mkdir /etc/nginx/html/test
touch /etc/nginx/html/test/index.html
echo "Hello World!" | sudo tee /etc/nginx/html/test/index.html > /dev/null


# Configure Nginx
sudo echo "server {
    listen 80;
    location / {
        echo 'Hello World!';
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart Nginx
sudo service nginx restart
