#!/usr/bin/env bash
# Deals with redirections

# define redirection variable
site="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
# site="\\\t rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"


# Install nginx
sudo apt-get update
sudo apt-get install nginx -y

# Create folders and files
# echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
# sudo sed -i "6i $site" /etc/nginx/sites-available/default
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://youtube.com/UCw4X_zayaSiuVYcqWpiaSWw;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
