#!/usr/bin/env bash
# Deals with redirections

# define redirection variable
site="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"

# Install nginx
sudo apt-get update
sudo apt-get install nginx -y

# Create folders and files
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "30i $site" /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx start
