#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect above requirements
# (this script will be run on the server itself)

# Install nginx
apt-get update
apt-get -y install nginx

# Create folders
mkdir /etc/nginx/html
# Create file
touch /etc/nginx/html/index.html

# Write to files
echo "Hello World!" > /etc/nginx/html/index.html
# Default configurations from server 1
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://youtube.com/UCw4X_zayaSiuVYcqWpiaSWw;
    }
    error_page 404 /404.html;
    location /404 {
    	root /etc/nginx/html;
	internal;
    }
}" > /etc/nginx/sites-available/default

str="add_header X-Served-By $HOSTNAME;"
sudo sed -i "6i  \\\t$str" /etc/nginx/sites-available/default
sudo sed -i "13i \\\t$str" /etc/nginx/sites-available/default


# Restart Nginx
service nginx restart
