#!/usr/bin/env bash
# Conscript that configures a server to the above requirements

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get install nginx -y

# Check Nginx status
sudo service nginx status

# Check Nginx configuration
sudo nginx -t

# Check for processes using port 80
sudo netstat -tuln | grep LISTEN

# Update Nginx configuration to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
