#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
# -display hours from 0 to 12
# - display minutes from 1 to 59
# Requirements:
# You must use the while loop (for and until are forbidden)

i=0
while [ $i -le 12 ]
do
	j=1
	while [ $j -le 59 ]
	do
		echo "$i:$j"
		j=$((j+1))
	done
	i=$((i+1))
done
